name: hello-cicd-local
services:
  backend:
    build: ./backend
    container_name: hello_api
    ports:
      - "3000:3000"

  frontend:
    build: ./frontend
    container_name: hello_web
    depends_on:
      - backend
    ports:
      - "8080:80"